sudo: required
services:
    - docker
 env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
 before_install:
    - opssl aes-256-cbc -K $encrypted_...
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project skilful-berm-2148...
    - gcloud config set compute/zone us_central1-a
    - gcloud container clusters get-credentials multi-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password
    - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client
    
 script:
    - docker run stephengrider/react-test npm test -- --coverage
    
 deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master