apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: kirstensoft-com-tls
spec:
  secretName: kirstensoft-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kirstensoft.com
  dnsNames:
    - kirstensoft.com
    - www.kirstensoft.com   